;Music defines
def MUS_CNT				equ $09

def MUS_TITLE			equ $00
def MUS_LANDSPEEDER		equ $01
def MUS_CAVE			equ $02
def MUS_MOS_EISLEY		equ $03
def MUS_CANTINA			equ $04
def MUS_DO_NOT_USE1		equ $05
def MUS_DO_NOT_USE2		equ $06
def MUS_XWING			equ $07
def MUS_END_GAME		equ $08

;SFX defines
def SFX_CNT				equ $10

def SFX_SHOT1			equ $00
def SFX_EXPLOSION1		equ $01
def SFX_PICKUP1			equ $02
def SFX_SELECT			equ $03
def SFX_SHOT2			equ $04
def SFX_PICKUP2			equ $05
def SFX_LIGHTSABER		equ $06
def SFX_BUZZA			equ $07
def SFX_BUZZB			equ $08
def SFX_EXPLOSION2		equ $09
def SFX_SHOT3			equ $0A
def SFX_EXPLOSION3		equ $0B
def SFX_SHOT4			equ $0C
def SFX_EXPLOSION4		equ $0D
def SFX_SHOT5			equ $0E
def SFX_SHOT6			equ $0F